project:
  type: website
  output-dir: docs

website:
  title: "SFD-CFB-USVI_Port_Sampling_Info_Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



